import type { ToolDefinition } from './registry.types';

export const TOOL_CATALOG: ToolDefinition[] = [
  {
    id: 'financeiro.consultar_boletos',
    name: 'Consultar Boletos',
    domain: 'Financeiro',
    specialist: 'financeiro',
    description: 'Busca boletos abertos e vencidos de um cliente.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'financeiro.emitir_segunda_via',
    name: 'Emitir 2ª Via de Boleto',
    domain: 'Financeiro',
    specialist: 'financeiro',
    description: 'Gera um PDF atualizado de cobrança.',
    version: '1.0.0',
    executionMode: 'confirm',
    status: 'active',
  },
  {
    id: 'comercial.consultar_propostas',
    name: 'Consultar Propostas',
    domain: 'Comercial',
    specialist: 'comercial',
    description: 'Lista orçamentos e propostas vinculadas a um CNPJ.',
    version: '1.1.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'comercial.iniciar_orcamento',
    name: 'Iniciar Orçamento',
    domain: 'Comercial',
    specialist: 'comercial',
    description: 'Inicia o wizard ou draft de uma nova proposta comercial.',
    version: '1.0.0',
    executionMode: 'confirm',
    status: 'active',
  },
  {
    id: 'comercial.analisar_margem',
    name: 'Analisar Margem de Proposta',
    domain: 'Comercial',
    specialist: 'comercial',
    description: 'Simula a lucratividade de uma cotação.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'clientes.consultar',
    name: 'Consultar Cadastro de Cliente',
    domain: 'Comercial',
    specialist: 'comercial',
    description: 'Verifica informações cadastrais via CNPJ.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'propostas.consultar_por_cliente',
    name: 'Consultar Propostas / Orçamentos do Cliente',
    domain: 'Comercial',
    specialist: 'comercial',
    description:
      'Busca as últimas propostas e orçamentos de um cliente em public.propostas. ' +
      'Modo somente leitura. Para orçamento: todos os status. Para pedido real: is_prd_aprovado=true.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'propostas.consultar_por_id_int',
    name: 'Consultar Proposta por id_int',
    domain: 'Comercial',
    specialist: 'comercial',
    description:
      'Busca uma proposta específica em public.propostas filtrando por id_int (chave transversal). ' +
      'Retorna: id_int, cliente, status_interno, valor_total, valor, data, vendedor, empresa. ' +
      'Fonte citada: public.propostas · filtro: id_int = N. Modo somente leitura.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'producao.consultar_status_pedido',
    name: 'Status de Produção',
    domain: 'Produção',
    specialist: 'producao',
    description: 'Verifica em qual ilha da fábrica uma OS se encontra.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'expedicao.simular_frete',
    name: 'Simular Frete',
    domain: 'Expedição',
    specialist: 'expedicao',
    description: 'Cota transportadoras baseado em peso e CEP.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'expedicao.rastrear_pedido',
    name: 'Rastrear Envio',
    domain: 'Expedição',
    specialist: 'expedicao',
    description: 'Busca o código de rastreamento de uma transportadora.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'produtos.consultar_catalogo',
    name: 'Consultar Catálogo',
    domain: 'Produtos',
    specialist: 'produtos',
    description: 'Busca ficha técnica de um item.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'produtos.verificar_estoque',
    name: 'Verificar Saldo de Estoque',
    domain: 'Produtos',
    specialist: 'produtos',
    description: 'Busca saldo em tempo real no almoxarifado.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'fiscal.consultar_nf',
    name: 'Consultar NF-e',
    domain: 'Fiscal',
    specialist: 'fiscal',
    description: 'Busca status de autorização na SEFAZ.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  },
  {
    id: 'fiscal.baixar_xml',
    name: 'Baixar XML',
    domain: 'Fiscal',
    specialist: 'fiscal',
    description: 'Realiza download do XML assinado.',
    version: '1.0.0',
    executionMode: 'confirm',
    status: 'active',
  },
  {
    id: 'sistema.exibir_ajuda',
    name: 'Manual do Sistema',
    domain: 'Sistema',
    specialist: 'geral',
    description: 'Busca tutoriais na base de conhecimento.',
    version: '1.0.0',
    executionMode: 'auto',
    status: 'active',
  }
];
