export const PROPOSTA_STATUS_BASE_NOVO = "NOVO";
export const PROPOSTA_STATUS_BASE_AGUARDANDO = "AGUARDANDO";
export const PROPOSTA_STATUS_BASE_APROVADO = "APROVADO";
export const PROPOSTA_STATUS_BASE_CANCELADO = "CANCELADO";

export const PROPOSTA_STATUS_GROUP_NFE_ELIGIBLE = [PROPOSTA_STATUS_BASE_APROVADO];
export const PROPOSTA_STATUS_GROUP_PRODUCAO_ELIGIBLE = [PROPOSTA_STATUS_BASE_APROVADO];
export const PROPOSTA_STATUS_GROUP_ATIVO = [PROPOSTA_STATUS_BASE_NOVO, PROPOSTA_STATUS_BASE_AGUARDANDO, PROPOSTA_STATUS_BASE_APROVADO];
export const PROPOSTA_STATUS_GROUP_ATIVO_CLIENTE = [PROPOSTA_STATUS_BASE_APROVADO, PROPOSTA_STATUS_BASE_AGUARDANDO];
