export const STATUS_PRODUCAO_LISTA = [
  "NOVO / EM ARTE",
  "AGUARDANDO / EM ARTE",
  "APROVADO / EM ARTE",
  "REVISAO PRODUCAO",
  "EM PRODUCAO",
  "EM IMPRESSAO",
  "EM ACABAMENTO",
  "REVISAO"
];
