import type { SupabaseNfeRow, NfeReadModel } from "./types";

export function mapSupabaseNfeRowToReadModel(row: SupabaseNfeRow): NfeReadModel {
  return {
    id: row.id,
    id_int: row.id_int,
    id_cliente: row.id_cliente,
    ref: row.ref,
    ambiente: row.ambiente,
    modelo: row.modelo,
    status: row.status,
    status_focus: row.status_focus,
    status_sefaz: row.status_sefaz,
    mensagem_sefaz: row.mensagem_sefaz,
    codigo_status_sefaz: row.codigo_status_sefaz,
    numero_nf: row.numero_nf,
    serie: row.serie,
    chave_nfe: row.chave_nfe,
    protocolo: row.protocolo,
    data_autorizacao: row.data_autorizacao,
    data_cancelamento: row.data_cancelamento,
    natureza_operacao: row.natureza_operacao,
    tipo_documento: row.tipo_documento,
    finalidade_emissao: row.finalidade_emissao,
    consumidor_final: row.consumidor_final,
    presenca_comprador: row.presenca_comprador,
    tipo_contribuinte: row.tipo_contribuinte,
    modalidade_frete: row.modalidade_frete,
    id_cotacao_frete: row.id_cotacao_frete,
    transportadora: row.transportadora,
    valor_frete: row.valor_frete,
    peso_liquido: row.peso_liquido,
    peso_bruto: row.peso_bruto,
    quantidade_volumes: row.quantidade_volumes,
    especie_volumes: row.especie_volumes,
    marca_volumes: row.marca_volumes,
    numeracao_volumes: row.numeracao_volumes,
    informacoes_complementares: row.informacoes_complementares,
    observacoes_internas: row.observacoes_internas,
    endereco_entrega_observacao: row.endereco_entrega_observacao,
    valor_produtos: row.valor_produtos,
    valor_desconto: row.valor_desconto,
    valor_total_nf: row.valor_total_nf,
    caminho_xml: row.caminho_xml,
    caminho_danfe: row.caminho_danfe,
    url_xml: row.url_xml,
    url_danfe: row.url_danfe,
    payload_envio: row.payload_envio,
    payload_retorno: row.payload_retorno,
    payload_webhook: row.payload_webhook,
    erro_codigo: row.erro_codigo,
    erro_mensagem: row.erro_mensagem,
    erros_validacao: row.erros_validacao,
    tentativas_envio: row.tentativas_envio,
    ultima_tentativa_em: row.ultima_tentativa_em,
    criado_por: row.criado_por,
    criado_por_nome: row.criado_por_nome,
    created_at: row.created_at,
    updated_at: row.updated_at,
    id_empresa: row.id_empresa,
    end_entrega: row.end_entrega,
    cond_pgto: row.cond_pgto,
    forma_pgto: row.forma_pgto,
    drop_natureza_op: row.drop_natureza_op,
    id_transportadora_cliente: row.id_transportadora_cliente,
    pgto_is_configurado: row.pgto_is_configurado,
    nome: row.nome || null,
    fantasia: row.fantasia || null,
    isMock: false
  };
}
