export type SupabaseNullableValue = string | number | bigint | boolean | null | undefined;

export type SupabasePagamentoV2Row = {
  id: string;
  id_pagamento?: SupabaseNullableValue;
  id_int?: SupabaseNullableValue;
  os_ideal?: SupabaseNullableValue;
  id_cliente?: SupabaseNullableValue;
  cliente?: SupabaseNullableValue;
  documento?: SupabaseNullableValue;
  empresa?: SupabaseNullableValue;
  id_empresa?: SupabaseNullableValue;
  tipo_cobranca?: SupabaseNullableValue;
  status?: SupabaseNullableValue;
  valor?: SupabaseNullableValue;
  vencimento?: SupabaseNullableValue;
  confirmado?: SupabaseNullableValue;
  paid_at?: SupabaseNullableValue;
  created_at?: SupabaseNullableValue;
  descricao?: SupabaseNullableValue;
  linha_digitavel?: SupabaseNullableValue;
  token_publico?: SupabaseNullableValue;
  cartao_status?: SupabaseNullableValue;
  atendente?: SupabaseNullableValue;
};

export type SupabaseBoletoRow = {
  id: string;
  id_int?: SupabaseNullableValue;
  parcela?: SupabaseNullableValue;
  total_parcelas?: SupabaseNullableValue;
  valor?: SupabaseNullableValue;
  valor_atualizado?: SupabaseNullableValue;
  vencimento?: SupabaseNullableValue;
  status?: SupabaseNullableValue;
  created_at?: SupabaseNullableValue;
  paid_at?: SupabaseNullableValue;
  empresa?: SupabaseNullableValue;
  nome_cliente?: SupabaseNullableValue;
  documento?: SupabaseNullableValue;
  id_cliente?: SupabaseNullableValue;
  id_empresa?: SupabaseNullableValue;
  n_nf?: SupabaseNullableValue;
  n_doc_boleto?: SupabaseNullableValue;
  descricao?: SupabaseNullableValue;
  is_faturado?: SupabaseNullableValue;
  is_avulso?: SupabaseNullableValue;
  id_pagamento?: SupabaseNullableValue;
  dias_atraso?: SupabaseNullableValue;
  data_vencido?: SupabaseNullableValue;
  linha_digitavel?: SupabaseNullableValue;
  codigo_barras?: SupabaseNullableValue;
  url_pdf?: SupabaseNullableValue;
  pdf_storage?: SupabaseNullableValue;
  id_boleto_c6?: SupabaseNullableValue;
  nosso_numero?: SupabaseNullableValue;
  ext_reference?: SupabaseNullableValue;
  deposito_conta?: SupabaseNullableValue;
  confirmado_por?: SupabaseNullableValue;
  is_prorrogado?: SupabaseNullableValue;
  motivo_prorg?: SupabaseNullableValue;
  dias_prorg?: SupabaseNullableValue;
};
