-- Migration 1a/2 — Conta Corrente (Pendências Financeiras): PREPARAÇÃO ADITIVA
-- Data: 2026-07-21
-- Status: PREPARADA — NÃO APLICADA. Não rodar `supabase db push`, SQL Editor, nem aplicar em produção.
-- Especificação: docs/business/CONTA-CORRENTE-FASE-1-PREPARACAO.md
--
-- Esta migration é 100% ADITIVA: nova tabela, colunas NULLABLE, novas RPCs.
-- NÃO revoga nenhum grant existente, NÃO altera RLS de tabela existente, NÃO adiciona
-- trigger de bloqueio. A aplicação atual continua funcionando sem qualquer alteração de
-- comportamento se somente esta migration (1a) for aplicada.
--
-- O cutover (lockdown de escrita direta em movimento_credito + append-only) está em
-- 20260721_conta_corrente_fase1b_cutover.sql e só deve ser aplicado depois que o código
-- da aplicação estiver usando as RPCs abaixo (já feito neste branch — ver relatório da Fase 1).
--
-- =====================================================================================
-- ⚠️ PRÉ-VOO OBRIGATÓRIO — rodar ANTES de aplicar (somente SELECT, no SQL Editor com
--    privilégio pleno). O dump `scratch/schema.sql` é snapshot, não catálogo vivo.
-- =====================================================================================
--
-- -- (1) Triggers realmente anexados às tabelas do cálculo soberano:
-- SELECT tgrelid::regclass AS tabela, tgname, pg_get_triggerdef(oid)
-- FROM pg_trigger WHERE NOT tgisinternal
--   AND tgrelid = ANY (ARRAY['public.propostas','public.produtos_proposta',
--                            'public.cotacao_frete','public.desconto_proposta']::regclass[]);
--
-- -- (2) Corpo das funções chamadas por esses triggers (confirmar que v4 é no-op e v3 não está anexado):
-- SELECT proname, prosrc FROM pg_proc
-- WHERE proname IN ('recalcular_proposta_v3','recalcular_proposta_v4','recalcular_proposta_v4_trigger');
--
-- -- (3) Tipos/precisão monetária reais:
-- SELECT table_name, column_name, data_type, numeric_precision, numeric_scale
-- FROM information_schema.columns
-- WHERE table_schema='public'
--   AND (table_name,column_name) IN
--       (('pagamentos_v2','valor'),('pagamentos_v2','id'),('movimento_credito','valor'),
--        ('movimento_credito','id'),('propostas','valor_total'),('propostas','id_int'),
--        ('clientes','id_cliente'),('produtos_proposta','id_int'));
--
-- -- (4) Estados existentes em pagamentos_v2 (criação/confirmação/cancelamento):
-- SELECT DISTINCT status, confirmado FROM public.pagamentos_v2 ORDER BY 1;
--
-- -- (5) Coluna real de item cancelado em produtos_proposta (o dump NÃO mostra status_item):
-- SELECT column_name, data_type FROM information_schema.columns
-- WHERE table_schema='public' AND table_name='produtos_proposta';
--   -- NOTA: o "total soberano" é calculado no servidor (getPropostaDetailById), que exclui itens
--   --       cancelados. A RPC cc_abrir_pendencia RECEBE esse total e NÃO lê propostas.valor_total.
--
-- -- (6) Políticas e grants atuais das tabelas afetadas:
-- SELECT schemaname, tablename, policyname, cmd, roles FROM pg_policies
-- WHERE tablename IN ('movimento_credito','pagamentos_v2');
-- SELECT grantee, privilege_type FROM information_schema.role_table_grants
-- WHERE table_schema='public' AND table_name='movimento_credito';
--
-- =====================================================================================

BEGIN;

-- =====================================================================================
-- SEÇÃO A — Tabela de estado: conta_corrente_pendencias
-- =====================================================================================
CREATE TABLE IF NOT EXISTS public.conta_corrente_pendencias (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_int          bigint  NOT NULL,               -- proposta de ORIGEM (obrigatória na v1)
    id_cliente      bigint  NOT NULL,               -- PRÉ-VOO: clientes.id_cliente é integer no dump
    direcao         text    NOT NULL,
    motivo          text    NOT NULL,
    valor_original  numeric(12,2) NOT NULL,
    valor_saldo     numeric(12,2) NOT NULL DEFAULT 0,   -- FONTE OPERACIONAL do saldo
    valor_reservado numeric(12,2) NOT NULL DEFAULT 0,
    status          text    NOT NULL DEFAULT 'ABERTA',
    chave_evento    uuid    NOT NULL,                    -- idempotência da abertura
    observacao      text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      uuid    NOT NULL,
    atualizado_em   timestamptz,
    encerrado_em    timestamptz,
    encerrado_por   uuid,
    motivo_encerramento text,
    CONSTRAINT ccp_direcao_chk  CHECK (direcao IN ('FAVOR_CLIENTE','FAVOR_EMPRESA')),
    CONSTRAINT ccp_motivo_chk   CHECK (motivo IN ('FRETE','PRODUTO_INCLUIDO','PRODUTO_REMOVIDO','PRODUTO_TROCADO','SERVICO_ALTERADO','OUTRO')),
    CONSTRAINT ccp_status_chk   CHECK (status IN ('ABERTA','PARCIALMENTE_RESOLVIDA','RESOLVIDA','CANCELADA')),
    CONSTRAINT ccp_valor_original_chk CHECK (valor_original >= 0.01),
    CONSTRAINT ccp_valor_saldo_chk    CHECK (valor_saldo = 0 OR valor_saldo >= 0.01),        -- sem resíduo em (0,00;0,01)
    CONSTRAINT ccp_valor_reservado_chk CHECK (valor_reservado = 0 OR valor_reservado >= 0.01),
    CONSTRAINT ccp_soma_chk     CHECK (valor_saldo + valor_reservado <= valor_original),
    CONSTRAINT fk_ccp_proposta  FOREIGN KEY (id_int) REFERENCES public.propostas(id_int),
    CONSTRAINT fk_ccp_cliente   FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ccp_chave_evento ON public.conta_corrente_pendencias (chave_evento);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ccp_uma_aberta_por_proposta
    ON public.conta_corrente_pendencias (id_int)
    WHERE status IN ('ABERTA','PARCIALMENTE_RESOLVIDA');
CREATE INDEX IF NOT EXISTS idx_ccp_id_cliente ON public.conta_corrente_pendencias (id_cliente);
CREATE INDEX IF NOT EXISTS idx_ccp_id_int     ON public.conta_corrente_pendencias (id_int);
CREATE INDEX IF NOT EXISTS idx_ccp_status     ON public.conta_corrente_pendencias (status);

-- RLS mínima desde já (não é o "cutover"): tabela NOVA, sem consumidor legado.
-- ENABLE + grants aqui; a policy USING de fato (escopo de empresa) só pode
-- ser criada depois que public.cc__id_empresa_proposta existir (Seção D) —
-- CREATE POLICY, ao contrário de um corpo de função, valida a expressão
-- USING imediatamente, então não aceita forward reference. Ver
-- "SEÇÃO D.0b — Policy de conta_corrente_pendencias" logo após os helpers.
ALTER TABLE public.conta_corrente_pendencias ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.conta_corrente_pendencias FROM anon;
GRANT SELECT ON public.conta_corrente_pendencias TO authenticated;   -- sem INSERT/UPDATE/DELETE

-- =====================================================================================
-- SEÇÃO B — Colunas estruturadas na razão: movimento_credito
--   Todas NULLABLE; não afeta registros legados; não altera cancelado=true/false;
--   RLS/grants de movimento_credito NÃO são tocados aqui (fica para o cutover 1b).
-- =====================================================================================
ALTER TABLE public.movimento_credito ADD COLUMN IF NOT EXISTS id_pendencia         bigint;
ALTER TABLE public.movimento_credito ADD COLUMN IF NOT EXISTS tipo_evento          text;
ALTER TABLE public.movimento_credito ADD COLUMN IF NOT EXISTS id_int_origem        bigint;
ALTER TABLE public.movimento_credito ADD COLUMN IF NOT EXISTS id_int_destino       bigint;
ALTER TABLE public.movimento_credito ADD COLUMN IF NOT EXISTS id_pagamento_destino uuid;
ALTER TABLE public.movimento_credito ADD COLUMN IF NOT EXISTS id_movimento_ref     bigint;
ALTER TABLE public.movimento_credito ADD COLUMN IF NOT EXISTS motivo_evento        text;
-- Chave de idempotência persistida para escrita via RPC de ajuste avulso
-- (mc_ajuste_avulso_criar — Seção E). Substitui a antiga deduplicação por
-- janela de tempo (60s) que descartava operações legítimas próximas no tempo.
ALTER TABLE public.movimento_credito ADD COLUMN IF NOT EXISTS chave_idempotencia   uuid;

ALTER TABLE public.movimento_credito
  ADD CONSTRAINT mc_tipo_evento_chk
  CHECK (tipo_evento IS NULL OR tipo_evento IN
    ('ABERTURA','USO_PEDIDO','DEVOLUCAO','BONIFICACAO','BAIXA','CANCELAMENTO','ESTORNO','ABATIMENTO_LEGADO'));
ALTER TABLE public.movimento_credito
  ADD CONSTRAINT fk_mc_pendencia FOREIGN KEY (id_pendencia) REFERENCES public.conta_corrente_pendencias(id);
ALTER TABLE public.movimento_credito
  ADD CONSTRAINT fk_mc_movimento_ref FOREIGN KEY (id_movimento_ref) REFERENCES public.movimento_credito(id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mc_estorno_unico
    ON public.movimento_credito (id_movimento_ref)
    WHERE tipo_evento = 'ESTORNO';
-- Idempotência determinística do fallback legado de abatimento de débito em
-- confirmar/route.ts (mc_confirmar_abatimento_legado — Seção E): chave é o
-- próprio id do pagamento (já único), não uma janela de tempo.
CREATE UNIQUE INDEX IF NOT EXISTS ux_mc_abatimento_legado_unico
    ON public.movimento_credito (id_pagamento_destino)
    WHERE tipo_evento = 'ABATIMENTO_LEGADO';
CREATE UNIQUE INDEX IF NOT EXISTS ux_mc_chave_idempotencia
    ON public.movimento_credito (chave_idempotencia)
    WHERE chave_idempotencia IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mc_id_pendencia ON public.movimento_credito (id_pendencia);

-- =====================================================================================
-- SEÇÃO C — Colunas aditivas em pagamentos_v2 (reserva de débito)
--   Apenas aditivo. Nenhum fluxo existente de pagamentos_v2/boletos é alterado.
-- =====================================================================================
ALTER TABLE public.pagamentos_v2 ADD COLUMN IF NOT EXISTS id_pendencia    bigint;
ALTER TABLE public.pagamentos_v2 ADD COLUMN IF NOT EXISTS valor_pendencia numeric(12,2);
ALTER TABLE public.pagamentos_v2 ADD COLUMN IF NOT EXISTS reserva_estado  text;
ALTER TABLE public.pagamentos_v2 ADD COLUMN IF NOT EXISTS chave_reserva   uuid;
-- Chave de idempotência persistida por tentativa de operação (usar-credito e
-- pagamento-combinado — aplicação IMEDIATA de crédito, sem reserva). Repetir a
-- mesma requisição com a mesma chave retorna o resultado anterior em vez de
-- criar um novo pagamento. Substitui a antiga deduplicação por janela de 5
-- minutos, que descartava operações legítimas próximas no tempo.
ALTER TABLE public.pagamentos_v2 ADD COLUMN IF NOT EXISTS chave_idempotencia uuid;

ALTER TABLE public.pagamentos_v2
  ADD CONSTRAINT pgv2_reserva_estado_chk
  CHECK (reserva_estado IS NULL OR reserva_estado IN ('RESERVA_ATIVA','RESERVA_CONFIRMADA','RESERVA_LIBERADA'));
ALTER TABLE public.pagamentos_v2
  ADD CONSTRAINT pgv2_valor_pendencia_chk
  CHECK (valor_pendencia IS NULL OR valor_pendencia >= 0.01);
ALTER TABLE public.pagamentos_v2
  ADD CONSTRAINT fk_pgv2_pendencia FOREIGN KEY (id_pendencia) REFERENCES public.conta_corrente_pendencias(id);
-- Os 4 campos de reserva são um grupo atômico: nunca meio preenchidos. Uma
-- linha sem reserva tem os 4 NULL; uma linha com reserva (ativa, confirmada
-- ou liberada) tem os 4 preenchidos — cc_usar_pendencia sempre grava os 4
-- juntos, e cc_encerrar_pendencia só altera reserva_estado (nunca limpa os
-- outros 3), então esta invariante já vale hoje; a CHECK só a torna explícita.
ALTER TABLE public.pagamentos_v2
  ADD CONSTRAINT pgv2_reserva_completa_chk
  CHECK (
    (id_pendencia IS NULL AND valor_pendencia IS NULL AND reserva_estado IS NULL AND chave_reserva IS NULL)
    OR
    (id_pendencia IS NOT NULL AND valor_pendencia IS NOT NULL AND reserva_estado IS NOT NULL AND chave_reserva IS NOT NULL)
  );

CREATE UNIQUE INDEX IF NOT EXISTS ux_pgv2_chave_reserva
    ON public.pagamentos_v2 (chave_reserva) WHERE chave_reserva IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_pgv2_reserva_ativa
    ON public.pagamentos_v2 (id_pendencia) WHERE reserva_estado = 'RESERVA_ATIVA';
CREATE UNIQUE INDEX IF NOT EXISTS ux_pgv2_chave_idempotencia
    ON public.pagamentos_v2 (chave_idempotencia) WHERE chave_idempotencia IS NOT NULL;

-- =====================================================================================
-- SEÇÃO C.1 — Proteção real das 5 colunas novas de pagamentos_v2
--   CONFIRMADO no catálogo vivo (pré-voo): pagamentos_v2 tem policy RLS
--   permissiva (`geral`, USING true, WITH CHECK true) e GRANT de
--   INSERT/UPDATE/DELETE/TRUNCATE em NÍVEL DE TABELA para anon e
--   authenticated.
--
--   CORREÇÃO (achado da revisão): um REVOKE INSERT/UPDATE (coluna) por si só
--   NÃO bloqueia nada enquanto o GRANT INSERT/UPDATE de tabela inteira
--   continuar valendo — no modelo de privilégios do Postgres, privilégio de
--   tabela e de coluna são cumulativos (OR), nunca um restringe o outro. É
--   preciso primeiro revogar INSERT/UPDATE na TABELA INTEIRA de
--   anon/authenticated, e só então conceder de volta, coluna a coluna,
--   apenas os campos legados que devem continuar editáveis. DELETE/TRUNCATE
--   não são tocados aqui (não têm granularidade de coluna — ficam para o
--   cutover 1b, que endurece a tabela como um todo).
--
--   A lista de colunas legadas é obtida do catálogo vivo (information_schema),
--   não hardcoded — evita esquecer alguma coluna existente e quebrar
--   silenciosamente um INSERT/UPDATE legado por omissão.
--
--   As 5 colunas protegidas (id_pendencia, valor_pendencia, reserva_estado,
--   chave_reserva, chave_idempotencia) ficam de fora do re-GRANT, tanto em
--   INSERT quanto em UPDATE: nenhuma delas pode mais ser definida
--   diretamente por anon/authenticated, nem na criação nem depois. A única
--   via de escrita passa a ser RPC SECURITY DEFINER (roda como dono da
--   tabela, imune a este REVOKE):
--     - id_pendencia/valor_pendencia/reserva_estado/chave_reserva →
--       cc_usar_pendencia / cc_encerrar_pendencia (Seção D).
--     - chave_idempotencia → pgv2_registrar_chave_idempotencia (Seção C.2),
--       chamada por usar-credito/route.ts e pagamento-combinado/route.ts
--       logo após o INSERT do pagamento (que agora NÃO inclui mais
--       chave_idempotencia no payload).
-- =====================================================================================
REVOKE INSERT, UPDATE ON public.pagamentos_v2 FROM anon, authenticated;

DO $$
DECLARE
  v_cols text;
BEGIN
  SELECT string_agg(quote_ident(column_name), ', ' ORDER BY ordinal_position)
    INTO v_cols
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'pagamentos_v2'
    AND column_name NOT IN ('id_pendencia','valor_pendencia','reserva_estado','chave_reserva','chave_idempotencia');

  IF v_cols IS NULL THEN
    RAISE EXCEPTION 'CC_MIGRACAO: nenhuma coluna legada encontrada em pagamentos_v2 — abortando para não conceder 0 colunas';
  END IF;

  EXECUTE format('GRANT INSERT (%s) ON public.pagamentos_v2 TO anon, authenticated', v_cols);
  EXECUTE format('GRANT UPDATE (%s) ON public.pagamentos_v2 TO anon, authenticated', v_cols);
END $$;

-- =====================================================================================
-- SEÇÃO C.2 — RPC: pgv2_registrar_chave_idempotencia
--   Único caminho para gravar pagamentos_v2.chave_idempotencia. Chamada
--   pelas rotas logo após o INSERT do pagamento (que não inclui mais essa
--   coluna).
--
--   Autorização em duas camadas — NÃO confia somente em credito.usar
--   (permissão global, sem recorte por linha):
--     1) cc__assert_permissao(credito.usar) — baseline, igual às demais RPCs.
--     2) Escopo de empresa da linha — MESMA regra oficial já usada em
--        cancelar-boleto/route.ts e cancelar-externo/route.ts para
--        pagamentos_v2: super_adm passa; qualquer outro usuário só age sobre
--        um pagamento cujo id_empresa bate com usuarios.id_empresa. Sem essa
--        camada, qualquer usuário com credito.usar poderia carimbar a chave
--        de idempotência de um pagamento de OUTRA empresa/proposta.
--
--   Trava a linha com FOR UPDATE antes de decidir, rejeita pagamento
--   CANCELADO, e só grava se chave_idempotencia ainda estiver NULL (checado
--   explicitamente sobre a linha já travada — mesma regra de antes, sem
--   repetir a condição no WHERE do UPDATE). O índice único
--   ux_pgv2_chave_idempotencia continua sendo quem impede duas linhas
--   diferentes com a mesma chave — não removido, não substituído.
-- =====================================================================================
CREATE OR REPLACE FUNCTION public.pgv2_registrar_chave_idempotencia(
  p_id_pagamento uuid, p_chave_idempotencia uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_pag public.pagamentos_v2%ROWTYPE;
  v_super public.usuarios.is_super_adm%TYPE;
  v_empresa_usuario public.usuarios.id_empresa%TYPE;
BEGIN
  PERFORM public.cc__assert_permissao(v_uid, 'credito.usar');
  IF p_id_pagamento IS NULL OR p_chave_idempotencia IS NULL THEN
    RAISE EXCEPTION 'MC_PARAMS: id_pagamento e chave_idempotencia são obrigatórios';
  END IF;

  SELECT * INTO v_pag FROM public.pagamentos_v2 WHERE id = p_id_pagamento FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'MC_PAGAMENTO: pagamento % não encontrado', p_id_pagamento;
  END IF;
  IF v_pag.status = 'CANCELADO' THEN
    RAISE EXCEPTION 'MC_CANCELADO: pagamento % está cancelado', p_id_pagamento;
  END IF;

  SELECT is_super_adm, id_empresa INTO v_super, v_empresa_usuario
    FROM public.usuarios WHERE user_id = v_uid;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'AUTH: usuário sem cadastro em public.usuarios' USING ERRCODE = '28000';
  END IF;
  IF COALESCE(v_super, false) = false THEN
    IF v_empresa_usuario IS NULL OR v_pag.id_empresa IS NULL OR v_empresa_usuario <> v_pag.id_empresa THEN
      RAISE EXCEPTION 'PERM: pagamento fora do escopo de empresa do usuário' USING ERRCODE = '42501';
    END IF;
  END IF;

  IF v_pag.chave_idempotencia IS NOT NULL THEN
    RAISE EXCEPTION 'MC_IDEMPOTENCIA: pagamento % já possui chave', p_id_pagamento;
  END IF;

  UPDATE public.pagamentos_v2
     SET chave_idempotencia = p_chave_idempotencia
   WHERE id = p_id_pagamento;
END; $$;

REVOKE ALL ON FUNCTION public.pgv2_registrar_chave_idempotencia(uuid,uuid) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.pgv2_registrar_chave_idempotencia(uuid,uuid) TO authenticated;

-- =====================================================================================
-- SEÇÃO D — Helpers internos (SECURITY DEFINER, search_path fixo)
-- =====================================================================================
CREATE OR REPLACE FUNCTION public.cc__assert_permissao(p_uid uuid, p_perm text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE v_super boolean; v_admin boolean; v_perfil bigint; v_perms text[];
BEGIN
  IF p_uid IS NULL THEN RAISE EXCEPTION 'AUTH: usuário não autenticado' USING ERRCODE = '28000'; END IF;
  SELECT is_super_adm, is_admin, id_perfil INTO v_super, v_admin, v_perfil
  FROM public.usuarios WHERE user_id = p_uid;
  IF NOT FOUND THEN RAISE EXCEPTION 'AUTH: usuário sem cadastro em public.usuarios' USING ERRCODE = '42501'; END IF;
  IF v_super THEN RETURN; END IF;
  IF p_perm = '__ADMIN__' THEN
    IF v_admin THEN RETURN; END IF;
    RAISE EXCEPTION 'PERM: operação restrita a administrador/superadministrador' USING ERRCODE = '42501';
  END IF;
  IF v_perfil IS NOT NULL THEN
    SELECT permissoes INTO v_perms FROM public.perfis WHERE id = v_perfil AND ativo = true;
    IF v_perms IS NOT NULL AND ('*' = ANY (v_perms) OR p_perm = ANY (v_perms)) THEN RETURN; END IF;
  END IF;
  IF v_admin THEN RETURN; END IF;
  RAISE EXCEPTION 'PERM: sem permissão %', p_perm USING ERRCODE = '42501';
END; $$;

CREATE OR REPLACE FUNCTION public.cc__status(p_original numeric, p_saldo numeric, p_reservado numeric)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE
    WHEN p_saldo = 0 AND p_reservado = 0 THEN 'RESOLVIDA'
    WHEN p_saldo = p_original AND p_reservado = 0 THEN 'ABERTA'
    ELSE 'PARCIALMENTE_RESOLVIDA'
  END;
$$;

CREATE OR REPLACE FUNCTION public.cc__timeline(p_id_int bigint, p_id_cliente bigint, p_msg text, p_uid uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN
  INSERT INTO public.propostas_chat (id_int, id_cliente, mensagem, tipo, autor_uid, autor_nome, setor, visivel_externo, anexos)
  VALUES (p_id_int, p_id_cliente, p_msg, 'SISTEMA', p_uid, 'Sistema — Conta Corrente', 'Financeiro', false, NULL);
END; $$;

-- Valor pago confirmado da proposta (recalculado no servidor; NÃO usa propostas.valor_total)
CREATE OR REPLACE FUNCTION public.cc__valor_pago(p_id_int bigint)
RETURNS numeric LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT COALESCE(round(SUM(
    GREATEST(0, COALESCE(valor,0) - COALESCE(
      (regexp_match(COALESCE(obs_v2,''), '\[ABATIMENTO_DEBITO:(\d+(?:\.\d{1,2})?)\]'))[1]::numeric, 0)))
  , 2), 0)
  FROM public.pagamentos_v2
  WHERE id_int = p_id_int
    AND status <> 'CANCELADO'
    AND (status = 'PAID' OR (status = 'A_VENCER' AND confirmado = true));
$$;

-- Resolve o id_empresa numérico (mesmo espaço de public.usuarios.id_empresa)
-- a partir de pagamentos_v2.id_empresa — a mesma fonte já usada por todo o
-- domínio financeiro (gerar-pix, cancelar-boleto, cancelar-externo), em vez
-- de propostas.empresa (texto livre, frequentemente NULL — ex.: proposta
-- #18087, que travava em editar-paga com "empresa inválida ou não
-- reconhecida ('null')"). Considera apenas cobranças não CANCELADAS da
-- proposta; se houver exatamente uma empresa entre elas, usa-a; se não
-- houver nenhuma ou houver mais de uma distinta, retorna NULL (os
-- chamadores — cc__assert_escopo_empresa e a policy RLS — já tratam NULL
-- como "fora do escopo"/sem acesso).
CREATE OR REPLACE FUNCTION public.cc__id_empresa_proposta(p_id_int bigint)
RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT CASE WHEN count(DISTINCT id_empresa) = 1 THEN min(id_empresa) ELSE NULL END
  FROM public.pagamentos_v2
  WHERE id_int = p_id_int
    AND status <> 'CANCELADO'
    AND id_empresa IS NOT NULL;
$$;

-- =====================================================================================
-- SEÇÃO D.0b — Policy de conta_corrente_pendencias (RLS por escopo de empresa)
--   Substitui o USING(true) provisório da Seção A agora que
--   cc__id_empresa_proposta existe. Superadmin acessa tudo; demais usuários
--   só veem pendências de propostas da própria empresa (mesma regra oficial
--   de escopo de empresa/proposta já usada no projeto).
-- =====================================================================================
CREATE POLICY ccp_select_authenticated ON public.conta_corrente_pendencias
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.usuarios u
      WHERE u.user_id = auth.uid()
        AND (
          COALESCE(u.is_super_adm, false)
          OR (u.id_empresa IS NOT NULL AND u.id_empresa = public.cc__id_empresa_proposta(conta_corrente_pendencias.id_int))
        )
    )
  );

-- Escopo de empresa oficial (mesma regra já usada em cancelar-boleto/route.ts
-- e cancelar-externo/route.ts para pagamentos_v2, aqui estendida a
-- propostas via cc__id_empresa_proposta): superadmin acessa tudo; qualquer
-- outro usuário só age sobre uma proposta cujo id_empresa resolvido bate com
-- usuarios.id_empresa. RAISE em caso de fora de escopo — nunca retorna
-- boolean para o chamador decidir (evita esquecer de checar o retorno).
CREATE OR REPLACE FUNCTION public.cc__assert_escopo_empresa(p_uid uuid, p_id_int bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_super public.usuarios.is_super_adm%TYPE;
  v_empresa_usuario public.usuarios.id_empresa%TYPE;
  v_empresa_proposta bigint;
BEGIN
  SELECT is_super_adm, id_empresa INTO v_super, v_empresa_usuario
    FROM public.usuarios WHERE user_id = p_uid;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'AUTH: usuário sem cadastro em public.usuarios' USING ERRCODE = '28000';
  END IF;
  IF COALESCE(v_super, false) THEN RETURN; END IF;

  v_empresa_proposta := public.cc__id_empresa_proposta(p_id_int);
  IF v_empresa_usuario IS NULL OR v_empresa_proposta IS NULL OR v_empresa_usuario <> v_empresa_proposta THEN
    RAISE EXCEPTION 'PERM: proposta #% fora do escopo de empresa do usuário', p_id_int USING ERRCODE = '42501';
  END IF;
END; $$;

-- Recalcula no banco o total soberano da proposta (mesma fórmula de
-- calculateResumo()/saveProposta() em orcamentos.service.ts e
-- orcamento-utils.ts — NÃO uma regra nova):
--   não-avulso: valorTotal = max(0, subtotalItensAtivos - descontoGeral + frete)
--     subtotalItensAtivos = SUM(produtos_proposta.valor_sub_total)
--       WHERE COALESCE(status_item,'PENDENTE') <> 'CANCELADO'
--     descontoGeral = min(subtotal, max(0, PERCENTUAL: subtotal*valor_percentual/100 | VALOR: valor_nominal))
--       fonte: desconto_proposta (tipo_desconto='DESCONTO_GERAL' ou NULL —
--       linhas legadas sem o tipo marcado também são desconto geral)
--     frete = propostas.valor_frete (frete já escolhido/persistido na proposta)
--   avulso: valorTotal = max(0, propostas.valor + propostas.valor_frete) — sem
--     itens em produtos_proposta e sem desconto geral, mesma regra do ramo
--     avulso de saveProposta/getPropostaDetailById.
CREATE OR REPLACE FUNCTION public.cc__total_soberano_proposta(p_id_int bigint)
RETURNS numeric LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_prop public.propostas%ROWTYPE;
  v_subtotal numeric;
  v_frete numeric;
  v_desc_pct numeric;
  v_desc_nom numeric;
  v_desconto numeric;
BEGIN
  SELECT * INTO v_prop FROM public.propostas WHERE id_int = p_id_int;
  IF NOT FOUND THEN RETURN NULL; END IF;

  v_frete := COALESCE(v_prop.valor_frete, 0);

  IF v_prop.is_avulso THEN
    RETURN GREATEST(0, round(COALESCE(v_prop.valor, 0) + v_frete, 2));
  END IF;

  SELECT COALESCE(SUM(valor_sub_total), 0) INTO v_subtotal
    FROM public.produtos_proposta
   WHERE id_int = p_id_int
     AND COALESCE(status_item, 'PENDENTE') <> 'CANCELADO';

  -- 'DESCONTO_GERAL' é o único tipo gravado pelo código (orcamentos.service.ts);
  -- tipo_desconto NULL ocorre em linhas legadas com o mesmo formato/uso (ex.:
  -- proposta #18087, desconto_proposta.id=75, tipo_desconto=NULL, descricao=
  -- 'Tabela especial') e precisa ser tratado como o mesmo desconto geral —
  -- caso contrário o helper ignora um desconto que o front já aplica (bug
  -- que causou CC_TOTAL_DIVERGENTE: informado R$3.741,50 x recalculado
  -- R$3.919,00, diferença de R$177,50 = 5% de R$3.550,00 do desconto perdido).
  SELECT valor_percentual, valor_nominal INTO v_desc_pct, v_desc_nom
    FROM public.desconto_proposta
   WHERE id_int = p_id_int AND (tipo_desconto = 'DESCONTO_GERAL' OR tipo_desconto IS NULL)
   ORDER BY (tipo_desconto = 'DESCONTO_GERAL') DESC, id DESC
   LIMIT 1;

  IF COALESCE(v_desc_pct, 0) > 0 THEN
    v_desconto := GREATEST(0, v_subtotal * v_desc_pct / 100);
  ELSE
    v_desconto := GREATEST(0, COALESCE(v_desc_nom, 0));
  END IF;
  v_desconto := LEAST(v_subtotal, v_desconto);

  RETURN GREATEST(0, round(v_subtotal + v_frete - v_desconto, 2));
END; $$;

-- =====================================================================================
-- SEÇÃO D.1 — RPC: cc_abrir_pendencia
-- =====================================================================================
CREATE OR REPLACE FUNCTION public.cc_abrir_pendencia(
  p_id_int bigint, p_id_cliente bigint, p_chave_evento uuid,
  p_motivo text, p_total_soberano numeric, p_observacao text DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_exist bigint; v_prop_cliente bigint;
  v_pago numeric; v_diff numeric; v_dir text; v_new numeric;
  v_open public.conta_corrente_pendencias%ROWTYPE;
  v_committed numeric; v_delta numeric; v_tipo text; v_new_id bigint;
  v_total_recalculado numeric;
BEGIN
  PERFORM public.cc__assert_permissao(v_uid, 'propostas.editar_paga');
  IF p_id_int IS NULL OR p_id_cliente IS NULL OR p_chave_evento IS NULL OR p_motivo IS NULL THEN
    RAISE EXCEPTION 'CC_PARAMS: id_int, id_cliente, chave_evento e motivo são obrigatórios';
  END IF;

  SELECT id INTO v_exist FROM public.conta_corrente_pendencias WHERE chave_evento = p_chave_evento;
  IF FOUND THEN RETURN v_exist; END IF;

  SELECT id_cliente INTO v_prop_cliente FROM public.propostas WHERE id_int = p_id_int;
  IF NOT FOUND THEN RAISE EXCEPTION 'CC_PROPOSTA: proposta #% não encontrada', p_id_int; END IF;

  -- p_id_cliente deve corresponder ao cliente real da proposta, nunca só o
  -- valor que o chamador informou.
  IF v_prop_cliente IS DISTINCT FROM p_id_cliente THEN
    RAISE EXCEPTION 'CC_CLIENTE: id_cliente informado (%) não corresponde ao cliente real da proposta #% (%)', p_id_cliente, p_id_int, v_prop_cliente;
  END IF;

  -- Escopo de empresa do usuário (mesma regra oficial já usada no projeto).
  PERFORM public.cc__assert_escopo_empresa(v_uid, p_id_int);

  v_pago := public.cc__valor_pago(p_id_int);

  -- A pendência só existe para diferença surgida DEPOIS que a proposta já
  -- está paga — sem pagamento confirmado não há "diferença" a registrar.
  IF v_pago <= 0 THEN
    RAISE EXCEPTION 'CC_NAO_PAGA: proposta #% não possui pagamento confirmado — Conta Corrente só se aplica a diferença após proposta paga', p_id_int;
  END IF;

  -- Não confia isoladamente em p_total_soberano: recalcula no banco (itens
  -- não CANCELADOS + frete escolhido + desconto geral) e rejeita divergência
  -- além de tolerância de arredondamento (R$ 0,02 — mesma tolerância já
  -- usada em resolver-diferenca/route.ts).
  v_total_recalculado := public.cc__total_soberano_proposta(p_id_int);
  IF v_total_recalculado IS NULL THEN
    RAISE EXCEPTION 'CC_TOTAL_INDISPONIVEL: não foi possível recalcular o total da proposta #%', p_id_int;
  END IF;
  IF abs(v_total_recalculado - p_total_soberano) > 0.02 THEN
    RAISE EXCEPTION 'CC_TOTAL_DIVERGENTE: total informado (R$ %) diverge do recalculado no banco (R$ %) para a proposta #%', p_total_soberano, v_total_recalculado, p_id_int;
  END IF;

  v_diff := round(p_total_soberano - v_pago, 2);
  v_dir  := CASE WHEN v_diff < 0 THEN 'FAVOR_CLIENTE' WHEN v_diff > 0 THEN 'FAVOR_EMPRESA' ELSE NULL END;
  v_new  := abs(v_diff);

  -- REGRA (2026-07-22): diferença DEVEDORA (novo total > pago) é saldo da
  -- própria proposta — resolvida por cobrança complementar, abono do
  -- administrador ou E-Crédito — e NUNCA entra na Conta Corrente. Trata como
  -- diferença zero para fins de pendência: encerra pendência aberta (se nada
  -- comprometido) e não cria pendência FAVOR_EMPRESA a partir deste fluxo.
  IF v_diff > 0 THEN
    v_dir := NULL;
    v_new := 0;
  END IF;

  SELECT * INTO v_open FROM public.conta_corrente_pendencias
   WHERE id_int = p_id_int AND status IN ('ABERTA','PARCIALMENTE_RESOLVIDA')
   FOR UPDATE;

  IF FOUND THEN
    v_committed := v_open.valor_reservado + (v_open.valor_original - v_open.valor_saldo - v_open.valor_reservado);
    IF v_dir IS NULL OR v_dir = v_open.direcao THEN
      IF v_new < 0.01 THEN
        IF v_committed > 0 THEN
          RAISE EXCEPTION 'CC_AJUSTE_ABAIXO_COMPROMETIDO: diferença zerada mas há valor já usado/reservado (R$ %) — revisão do financeiro necessária', v_committed;
        END IF;
        IF v_open.valor_saldo > 0 THEN
          INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
                 id_pendencia, tipo_evento, id_int_origem, motivo_evento)
          VALUES (p_id_cliente, p_id_int, v_open.valor_saldo,
                 CASE WHEN v_open.direcao = 'FAVOR_CLIENTE' THEN 'DEBITO' ELSE 'CREDITO' END,
                 'SISTEMA', 'Diferença zerada após nova alteração da proposta.', v_uid,
                 v_open.id, 'CANCELAMENTO', p_id_int, 'DIFERENCA_ZERADA');
        END IF;
        UPDATE public.conta_corrente_pendencias
           SET valor_saldo = 0, status = 'CANCELADA', encerrado_em = now(), encerrado_por = v_uid,
               motivo_encerramento = 'DIFERENCA_ZERADA', atualizado_em = now()
         WHERE id = v_open.id;
        PERFORM public.cc__timeline(p_id_int, p_id_cliente,
          '✔️ Pendência encerrada: diferença financeira zerada após nova alteração.', v_uid);
        RETURN v_open.id;
      END IF;
      IF v_new < v_committed - 0.001 THEN
        RAISE EXCEPTION 'CC_AJUSTE_ABAIXO_COMPROMETIDO: nova diferença (R$ %) menor que o já comprometido (R$ %) — revisão do financeiro necessária', v_new, v_committed;
      END IF;
      v_delta := round(v_new - v_open.valor_original, 2);
      IF v_delta <> 0 THEN
        v_tipo := CASE
          WHEN (v_open.direcao = 'FAVOR_CLIENTE' AND v_delta > 0) OR (v_open.direcao = 'FAVOR_EMPRESA' AND v_delta < 0) THEN 'CREDITO'
          ELSE 'DEBITO' END;
        INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
               id_pendencia, tipo_evento, id_int_origem, motivo_evento)
        VALUES (p_id_cliente, p_id_int, abs(v_delta), v_tipo, 'SISTEMA',
               'Ajuste de diferença da pendência (reconciliação).', v_uid,
               v_open.id, 'ABERTURA', p_id_int, p_motivo);
        UPDATE public.conta_corrente_pendencias
           SET valor_original = v_new, valor_saldo = valor_saldo + v_delta,
               status = public.cc__status(v_new, valor_saldo + v_delta, valor_reservado),
               atualizado_em = now()
         WHERE id = v_open.id;
        PERFORM public.cc__timeline(p_id_int, p_id_cliente,
          format('🔁 Pendência ajustada para R$ %s (%s).', to_char(v_new,'FM999999990.00'), v_open.direcao), v_uid);
      END IF;
      RETURN v_open.id;
    ELSE
      IF v_committed > 0 THEN
        RAISE EXCEPTION 'CC_FLIP_COM_COMPROMETIDO: inversão de direção com valor já usado/reservado — revisão do financeiro necessária';
      END IF;
      INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
             id_pendencia, tipo_evento, id_int_origem, motivo_evento)
      VALUES (p_id_cliente, p_id_int, v_open.valor_saldo,
             CASE WHEN v_open.direcao = 'FAVOR_CLIENTE' THEN 'DEBITO' ELSE 'CREDITO' END,
             'SISTEMA', 'Encerramento por inversão de direção.', v_uid,
             v_open.id, 'CANCELAMENTO', p_id_int, 'INVERSAO_DIRECAO');
      UPDATE public.conta_corrente_pendencias
         SET valor_saldo = 0, status = 'CANCELADA', encerrado_em = now(), encerrado_por = v_uid,
             motivo_encerramento = 'INVERSAO_DIRECAO', atualizado_em = now()
       WHERE id = v_open.id;
    END IF;
  END IF;

  IF v_new < 0.01 THEN RETURN NULL; END IF;
  INSERT INTO public.conta_corrente_pendencias
    (id_int, id_cliente, direcao, motivo, valor_original, valor_saldo, valor_reservado, status, chave_evento, observacao, created_by)
  VALUES (p_id_int, p_id_cliente, v_dir, p_motivo, v_new, v_new, 0, 'ABERTA', p_chave_evento, p_observacao, v_uid)
  RETURNING id INTO v_new_id;

  INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
         id_pendencia, tipo_evento, id_int_origem, motivo_evento)
  VALUES (p_id_cliente, p_id_int, v_new,
         CASE WHEN v_dir = 'FAVOR_CLIENTE' THEN 'CREDITO' ELSE 'DEBITO' END,
         'SISTEMA', 'Abertura de pendência por alteração de proposta paga.', v_uid,
         v_new_id, 'ABERTURA', p_id_int, p_motivo);

  PERFORM public.cc__timeline(p_id_int, p_id_cliente,
    format('🧾 Pendência aberta: R$ %s a favor de %s (motivo: %s).',
           to_char(v_new,'FM999999990.00'),
           CASE WHEN v_dir='FAVOR_CLIENTE' THEN 'cliente' ELSE 'empresa' END, p_motivo), v_uid);

  RETURN v_new_id;
END; $$;

-- =====================================================================================
-- SEÇÃO D.2 — RPC: cc_usar_pendencia
-- =====================================================================================
CREATE OR REPLACE FUNCTION public.cc_usar_pendencia(
  p_id_pendencia bigint, p_valor numeric, p_modo text,
  p_id_int_destino bigint DEFAULT NULL, p_id_pagamento uuid DEFAULT NULL,
  p_chave_reserva uuid DEFAULT NULL, p_observacao text DEFAULT NULL)
-- Retorna o id do lançamento em movimento_credito criado (CREDITO_IMEDIATO),
-- para permitir estorno pontual em rollback de consumo multi-pendência (FIFO)
-- feito pelo chamador. RESERVA_DEBITO não grava razão ainda — retorna NULL.
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_p public.conta_corrente_pendencias%ROWTYPE;
  v_pag public.pagamentos_v2%ROWTYPE;
  v_valor numeric; v_rem numeric; v_dummy int; v_movimento_id bigint;
BEGIN
  PERFORM public.cc__assert_permissao(v_uid, 'credito.usar');
  v_valor := round(p_valor, 2);
  IF v_valor < 0.01 THEN RAISE EXCEPTION 'CC_VALOR_MINIMO: uso mínimo é R$ 0,01'; END IF;

  SELECT * INTO v_p FROM public.conta_corrente_pendencias WHERE id = p_id_pendencia FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'CC_PENDENCIA: pendência % não encontrada', p_id_pendencia; END IF;
  IF v_p.status NOT IN ('ABERTA','PARCIALMENTE_RESOLVIDA') THEN
    RAISE EXCEPTION 'CC_STATUS: pendência não utilizável (status %)', v_p.status;
  END IF;

  -- Escopo de empresa da pendência (mesma regra oficial já usada no projeto).
  PERFORM public.cc__assert_escopo_empresa(v_uid, v_p.id_int);

  IF v_valor > v_p.valor_saldo THEN
    RAISE EXCEPTION 'CC_SALDO_INSUFICIENTE: saldo R$ % < solicitado R$ %', v_p.valor_saldo, v_valor;
  END IF;
  v_rem := round(v_p.valor_saldo - v_valor, 2);
  IF v_rem > 0 AND v_rem < 0.01 THEN RAISE EXCEPTION 'CC_RESIDUO: saldo residual entre R$ 0,00 e R$ 0,01 não é permitido'; END IF;

  IF p_modo = 'CREDITO_IMEDIATO' THEN
    IF v_p.direcao <> 'FAVOR_CLIENTE' THEN RAISE EXCEPTION 'CC_MODO: CREDITO_IMEDIATO exige direção FAVOR_CLIENTE'; END IF;
    UPDATE public.conta_corrente_pendencias
       SET valor_saldo = v_rem, status = public.cc__status(valor_original, v_rem, valor_reservado), atualizado_em = now()
     WHERE id = p_id_pendencia;
    INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
           id_pendencia, tipo_evento, id_int_origem, id_int_destino, id_pagamento_destino, motivo_evento)
    VALUES (v_p.id_cliente, v_p.id_int, v_valor, 'DEBITO', 'MANUAL',
           COALESCE(p_observacao,'Crédito aplicado como pagamento.'), v_uid,
           v_p.id, 'USO_PEDIDO', v_p.id_int, p_id_int_destino, p_id_pagamento, 'USO_CREDITO')
    RETURNING id INTO v_movimento_id;
    PERFORM public.cc__timeline(v_p.id_int, v_p.id_cliente,
      format('💰 Crédito de R$ %s aplicado como pagamento. Saldo restante: R$ %s.',
             to_char(v_valor,'FM999999990.00'), to_char(v_rem,'FM999999990.00')), v_uid);
    RETURN v_movimento_id;

  ELSIF p_modo = 'RESERVA_DEBITO' THEN
    IF v_p.direcao <> 'FAVOR_EMPRESA' THEN RAISE EXCEPTION 'CC_MODO: RESERVA_DEBITO exige direção FAVOR_EMPRESA'; END IF;
    IF p_id_pagamento IS NULL OR p_chave_reserva IS NULL THEN RAISE EXCEPTION 'CC_MODO: id_pagamento e chave_reserva são obrigatórios na reserva'; END IF;
    SELECT 1 INTO v_dummy FROM public.pagamentos_v2 WHERE chave_reserva = p_chave_reserva;
    IF FOUND THEN RETURN NULL; END IF;

    -- Trava o pagamento antes de decidir: nunca UPDATE às cegas. Rejeita
    -- CANCELADO, rejeita reserva já existente (nunca sobrescreve), e exige
    -- que pagamento e proposta de destino pertençam ao MESMO cliente e à
    -- mesma empresa da pendência.
    SELECT * INTO v_pag FROM public.pagamentos_v2 WHERE id = p_id_pagamento FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'CC_COBRANCA: pagamento % não encontrado para reserva', p_id_pagamento; END IF;
    IF v_pag.status = 'CANCELADO' THEN
      RAISE EXCEPTION 'CC_COBRANCA_CANCELADA: pagamento % está cancelado', p_id_pagamento;
    END IF;
    IF v_pag.id_pendencia IS NOT NULL OR v_pag.reserva_estado IS NOT NULL THEN
      RAISE EXCEPTION 'CC_RESERVA_EXISTENTE: pagamento % já está vinculado a outra reserva', p_id_pagamento;
    END IF;
    IF v_pag.id_cliente IS DISTINCT FROM v_p.id_cliente THEN
      RAISE EXCEPTION 'CC_CLIENTE_DIVERGENTE: pagamento % pertence a outro cliente', p_id_pagamento;
    END IF;
    IF p_id_int_destino IS NOT NULL AND v_pag.id_int IS DISTINCT FROM p_id_int_destino THEN
      RAISE EXCEPTION 'CC_PROPOSTA_DIVERGENTE: pagamento % não pertence à proposta de destino informada', p_id_pagamento;
    END IF;
    IF v_pag.id_empresa IS NOT NULL AND v_pag.id_empresa <> public.cc__id_empresa_proposta(v_p.id_int) THEN
      RAISE EXCEPTION 'CC_EMPRESA_DIVERGENTE: pagamento % pertence a outra empresa', p_id_pagamento;
    END IF;

    UPDATE public.conta_corrente_pendencias
       SET valor_saldo = v_rem, valor_reservado = valor_reservado + v_valor,
           status = public.cc__status(valor_original, v_rem, valor_reservado + v_valor), atualizado_em = now()
     WHERE id = p_id_pendencia;
    UPDATE public.pagamentos_v2
       SET id_pendencia = p_id_pendencia, valor_pendencia = v_valor,
           reserva_estado = 'RESERVA_ATIVA', chave_reserva = p_chave_reserva
     WHERE id = p_id_pagamento;
    PERFORM public.cc__timeline(v_p.id_int, v_p.id_cliente,
      format('📌 Débito de R$ %s reservado à cobrança do novo pedido (aguarda recebimento).',
             to_char(v_valor,'FM999999990.00')), v_uid);
    RETURN NULL;
  ELSE
    RAISE EXCEPTION 'CC_MODO: modo inválido %', p_modo;
  END IF;
END; $$;

-- =====================================================================================
-- SEÇÃO D.3 — RPC: cc_encerrar_pendencia
-- =====================================================================================
CREATE OR REPLACE FUNCTION public.cc_encerrar_pendencia(
  p_id_pendencia bigint, p_modo text, p_valor numeric DEFAULT NULL,
  p_id_movimento_ref bigint DEFAULT NULL, p_chave_reserva uuid DEFAULT NULL,
  p_motivo text DEFAULT NULL, p_observacao text DEFAULT NULL,
  p_id_pendencia_credito bigint DEFAULT NULL)
-- p_id_pendencia_credito: exclusivo do modo ABATER_DEBITO — pendência de
-- CRÉDITO (FAVOR_CLIENTE) consumida para baixar a pendência de DÉBITO
-- (p_id_pendencia, FAVOR_EMPRESA) na MESMA invocação/transação (ver bloco
-- ABATER_DEBITO abaixo — operação atômica, nunca duas chamadas separadas).
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_p public.conta_corrente_pendencias%ROWTYPE;
  v_cred public.conta_corrente_pendencias%ROWTYPE;
  v_res public.pagamentos_v2%ROWTYPE;
  v_ref public.movimento_credito%ROWTYPE;
  v_valor numeric; v_rem numeric; v_rem_cred numeric; v_tipo text; v_free numeric; v_mc_debito_id bigint;
BEGIN
  IF p_modo = 'CONFIRMAR_RESERVA' THEN
    -- Confirmação de recebimento é ato de conferência financeira, não de uso
    -- de crédito — exige a permissão correspondente (mesma já usada pela
    -- rota chamadora /api/cobrancas/confirmar).
    PERFORM public.cc__assert_permissao(v_uid, 'conferencia.confirm');
    SELECT * INTO v_res FROM public.pagamentos_v2
      WHERE chave_reserva = p_chave_reserva AND reserva_estado = 'RESERVA_ATIVA' AND id_pendencia = p_id_pendencia;
    IF NOT FOUND THEN RAISE EXCEPTION 'CC_RESERVA: reserva ativa não encontrada para a chave informada'; END IF;
    -- Só confirma o que realmente foi recebido — mesmo critério de
    -- cc__valor_pago (PAID, ou A_VENCER já confirmado).
    IF NOT (v_res.status = 'PAID' OR (v_res.status = 'A_VENCER' AND v_res.confirmado = true)) THEN
      RAISE EXCEPTION 'CC_NAO_RECEBIDO: pagamento % não está confirmado como recebido (status %)', v_res.id, v_res.status;
    END IF;
    SELECT * INTO v_p FROM public.conta_corrente_pendencias WHERE id = p_id_pendencia FOR UPDATE;
    IF v_res.id_cliente IS DISTINCT FROM v_p.id_cliente THEN
      RAISE EXCEPTION 'CC_CLIENTE_DIVERGENTE: pagamento % pertence a outro cliente', v_res.id;
    END IF;
    PERFORM public.cc__assert_escopo_empresa(v_uid, v_p.id_int);
    v_valor := v_res.valor_pendencia;
    UPDATE public.conta_corrente_pendencias
       SET valor_reservado = valor_reservado - v_valor,
           status = public.cc__status(valor_original, valor_saldo, valor_reservado - v_valor), atualizado_em = now()
     WHERE id = p_id_pendencia;
    INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
           id_pendencia, tipo_evento, id_int_origem, id_int_destino, id_pagamento_destino, motivo_evento)
    VALUES (v_p.id_cliente, v_p.id_int, v_valor, 'CREDITO', 'MANUAL',
           COALESCE(p_observacao,'Débito recebido na cobrança do novo pedido.'), v_uid,
           v_p.id, 'USO_PEDIDO', v_p.id_int, v_res.id_int, v_res.id, 'CONFIRMACAO_DEBITO');
    UPDATE public.pagamentos_v2 SET reserva_estado = 'RESERVA_CONFIRMADA' WHERE id = v_res.id;
    PERFORM public.cc__timeline(v_p.id_int, v_p.id_cliente,
      format('✅ Débito de R$ %s confirmado (recebido).', to_char(v_valor,'FM999999990.00')), v_uid);

  ELSIF p_modo = 'LIBERAR_RESERVA' THEN
    PERFORM public.cc__assert_permissao(v_uid, 'credito.usar');
    SELECT * INTO v_res FROM public.pagamentos_v2
      WHERE chave_reserva = p_chave_reserva AND reserva_estado = 'RESERVA_ATIVA' AND id_pendencia = p_id_pendencia;
    IF NOT FOUND THEN RAISE EXCEPTION 'CC_RESERVA: reserva ativa não encontrada'; END IF;
    SELECT * INTO v_p FROM public.conta_corrente_pendencias WHERE id = p_id_pendencia FOR UPDATE;
    IF v_res.id_cliente IS DISTINCT FROM v_p.id_cliente THEN
      RAISE EXCEPTION 'CC_CLIENTE_DIVERGENTE: pagamento % pertence a outro cliente', v_res.id;
    END IF;
    PERFORM public.cc__assert_escopo_empresa(v_uid, v_p.id_int);
    v_valor := v_res.valor_pendencia;
    UPDATE public.conta_corrente_pendencias
       SET valor_reservado = valor_reservado - v_valor, valor_saldo = valor_saldo + v_valor,
           status = public.cc__status(valor_original, valor_saldo + v_valor, valor_reservado - v_valor), atualizado_em = now()
     WHERE id = p_id_pendencia;
    UPDATE public.pagamentos_v2 SET reserva_estado = 'RESERVA_LIBERADA' WHERE id = v_res.id;
    PERFORM public.cc__timeline(v_p.id_int, v_p.id_cliente,
      format('↩️ Reserva de R$ %s liberada (cobrança falhou/cancelada). Débito volta a ficar disponível.',
             to_char(v_valor,'FM999999990.00')), v_uid);

  ELSIF p_modo IN ('DEVOLUCAO','BONIFICACAO','BAIXA') THEN
    PERFORM public.cc__assert_permissao(v_uid, CASE p_modo
      WHEN 'DEVOLUCAO' THEN 'financeiro.devolver'
      WHEN 'BONIFICACAO' THEN 'financeiro.bonificar'
      ELSE 'financeiro.resolver_credito' END);
    v_valor := round(p_valor, 2);
    IF v_valor < 0.01 THEN RAISE EXCEPTION 'CC_VALOR_MINIMO: mínimo R$ 0,01'; END IF;
    SELECT * INTO v_p FROM public.conta_corrente_pendencias WHERE id = p_id_pendencia FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'CC_PENDENCIA: não encontrada'; END IF;
    -- Guarda de direção: DEVOLUCAO é exclusiva de crédito ao cliente;
    -- BONIFICACAO/BAIXA são exclusivas de débito a favor da empresa. Sem esta
    -- checagem, ex. BONIFICACAO numa pendência FAVOR_CLIENTE aumentaria o
    -- crédito em vez de resolver um débito.
    IF p_modo = 'DEVOLUCAO' AND v_p.direcao <> 'FAVOR_CLIENTE' THEN
      RAISE EXCEPTION 'CC_MODO: DEVOLUCAO exige direção FAVOR_CLIENTE';
    END IF;
    IF p_modo IN ('BONIFICACAO','BAIXA') AND v_p.direcao <> 'FAVOR_EMPRESA' THEN
      RAISE EXCEPTION 'CC_MODO: % exige direção FAVOR_EMPRESA', p_modo;
    END IF;
    PERFORM public.cc__assert_escopo_empresa(v_uid, v_p.id_int);
    IF v_valor > v_p.valor_saldo THEN RAISE EXCEPTION 'CC_SALDO_INSUFICIENTE'; END IF;
    v_rem := round(v_p.valor_saldo - v_valor, 2);
    IF v_rem > 0 AND v_rem < 0.01 THEN RAISE EXCEPTION 'CC_RESIDUO'; END IF;
    v_tipo := CASE p_modo WHEN 'DEVOLUCAO' THEN 'DEBITO' ELSE 'CREDITO' END;
    UPDATE public.conta_corrente_pendencias
       SET valor_saldo = v_rem, status = public.cc__status(valor_original, v_rem, valor_reservado),
           atualizado_em = now(),
           encerrado_em = CASE WHEN v_rem = 0 AND valor_reservado = 0 THEN now() ELSE encerrado_em END,
           encerrado_por = CASE WHEN v_rem = 0 AND valor_reservado = 0 THEN v_uid ELSE encerrado_por END
     WHERE id = p_id_pendencia;
    INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
           id_pendencia, tipo_evento, id_int_origem, motivo_evento)
    VALUES (v_p.id_cliente, v_p.id_int, v_valor, v_tipo, 'MANUAL', p_observacao, v_uid,
           v_p.id, p_modo, v_p.id_int, p_motivo);
    PERFORM public.cc__timeline(v_p.id_int, v_p.id_cliente,
      format('%s de R$ %s registrada.', initcap(p_modo), to_char(v_valor,'FM999999990.00')), v_uid);

  ELSIF p_modo = 'ABATER_DEBITO' THEN
    -- Operação composta ATÔMICA (uma única invocação de RPC = uma única
    -- transação de banco): consome a pendência de CRÉDITO
    -- (p_id_pendencia_credito) para baixar a pendência de DÉBITO
    -- (p_id_pendencia). Substitui o padrão anterior de duas chamadas de RPC
    -- separadas (não atômicas entre si, com risco de estado parcialmente
    -- concluído). Se qualquer validação falhar após uma das duas pendências
    -- já ter sido lida/travada, o ROLLBACK implícito da função desfaz tudo —
    -- nunca fica em estado intermediário visível a outra sessão.
    PERFORM public.cc__assert_permissao(v_uid, 'financeiro.resolver_credito');
    v_valor := round(p_valor, 2);
    IF v_valor < 0.01 THEN RAISE EXCEPTION 'CC_VALOR_MINIMO: mínimo R$ 0,01'; END IF;
    IF p_id_pendencia_credito IS NULL THEN RAISE EXCEPTION 'CC_PARAMS: id_pendencia_credito é obrigatório em ABATER_DEBITO'; END IF;
    IF p_id_pendencia_credito = p_id_pendencia THEN RAISE EXCEPTION 'CC_PARAMS: pendência de débito e de crédito devem ser diferentes'; END IF;

    -- Ordem determinística de lock (menor id primeiro) evita deadlock entre
    -- abatimentos concorrentes que envolvam as duas mesmas pendências em ordem trocada.
    IF p_id_pendencia < p_id_pendencia_credito THEN
      SELECT * INTO v_p    FROM public.conta_corrente_pendencias WHERE id = p_id_pendencia         FOR UPDATE;
      SELECT * INTO v_cred FROM public.conta_corrente_pendencias WHERE id = p_id_pendencia_credito  FOR UPDATE;
    ELSE
      SELECT * INTO v_cred FROM public.conta_corrente_pendencias WHERE id = p_id_pendencia_credito  FOR UPDATE;
      SELECT * INTO v_p    FROM public.conta_corrente_pendencias WHERE id = p_id_pendencia          FOR UPDATE;
    END IF;
    IF v_p.id IS NULL THEN RAISE EXCEPTION 'CC_PENDENCIA: pendência de débito % não encontrada', p_id_pendencia; END IF;
    IF v_cred.id IS NULL THEN RAISE EXCEPTION 'CC_PENDENCIA: pendência de crédito % não encontrada', p_id_pendencia_credito; END IF;
    IF v_p.direcao <> 'FAVOR_EMPRESA' THEN RAISE EXCEPTION 'CC_MODO: ABATER_DEBITO exige pendência de débito com direção FAVOR_EMPRESA'; END IF;
    IF v_cred.direcao <> 'FAVOR_CLIENTE' THEN RAISE EXCEPTION 'CC_MODO: ABATER_DEBITO exige pendência de crédito com direção FAVOR_CLIENTE'; END IF;
    IF v_p.status NOT IN ('ABERTA','PARCIALMENTE_RESOLVIDA') THEN RAISE EXCEPTION 'CC_STATUS: pendência de débito não utilizável (status %)', v_p.status; END IF;
    IF v_cred.status NOT IN ('ABERTA','PARCIALMENTE_RESOLVIDA') THEN RAISE EXCEPTION 'CC_STATUS: pendência de crédito não utilizável (status %)', v_cred.status; END IF;
    IF v_p.id_cliente <> v_cred.id_cliente THEN
      RAISE EXCEPTION 'CC_CLIENTE_DIVERGENTE: crédito e débito devem pertencer ao mesmo cliente';
    END IF;
    PERFORM public.cc__assert_escopo_empresa(v_uid, v_p.id_int);
    PERFORM public.cc__assert_escopo_empresa(v_uid, v_cred.id_int);
    IF v_valor > v_p.valor_saldo THEN RAISE EXCEPTION 'CC_SALDO_INSUFICIENTE: saldo do débito R$ % < solicitado R$ %', v_p.valor_saldo, v_valor; END IF;
    IF v_valor > v_cred.valor_saldo THEN RAISE EXCEPTION 'CC_SALDO_INSUFICIENTE: saldo do crédito R$ % < solicitado R$ %', v_cred.valor_saldo, v_valor; END IF;

    v_rem := round(v_p.valor_saldo - v_valor, 2);
    IF v_rem > 0 AND v_rem < 0.01 THEN RAISE EXCEPTION 'CC_RESIDUO: saldo residual do débito entre R$ 0,00 e R$ 0,01 não é permitido'; END IF;
    v_rem_cred := round(v_cred.valor_saldo - v_valor, 2);
    IF v_rem_cred > 0 AND v_rem_cred < 0.01 THEN RAISE EXCEPTION 'CC_RESIDUO: saldo residual do crédito entre R$ 0,00 e R$ 0,01 não é permitido'; END IF;

    -- (1) Baixa a pendência de débito (empresa recebe via crédito do cliente).
    UPDATE public.conta_corrente_pendencias
       SET valor_saldo = v_rem, status = public.cc__status(valor_original, v_rem, valor_reservado),
           atualizado_em = now(),
           encerrado_em = CASE WHEN v_rem = 0 AND valor_reservado = 0 THEN now() ELSE encerrado_em END,
           encerrado_por = CASE WHEN v_rem = 0 AND valor_reservado = 0 THEN v_uid ELSE encerrado_por END
     WHERE id = v_p.id;
    INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
           id_pendencia, tipo_evento, id_int_origem, id_int_destino, motivo_evento)
    VALUES (v_p.id_cliente, v_p.id_int, v_valor, 'CREDITO', 'MANUAL', p_observacao, v_uid,
           v_p.id, 'BAIXA', v_p.id_int, v_cred.id_int, p_motivo)
    RETURNING id INTO v_mc_debito_id;

    -- (2) Consome a pendência de crédito na mesma proporção (efeito de "usar o
    -- crédito para pagar o débito"), referenciando o lançamento acima.
    UPDATE public.conta_corrente_pendencias
       SET valor_saldo = v_rem_cred, status = public.cc__status(valor_original, v_rem_cred, valor_reservado),
           atualizado_em = now(),
           encerrado_em = CASE WHEN v_rem_cred = 0 AND valor_reservado = 0 THEN now() ELSE encerrado_em END,
           encerrado_por = CASE WHEN v_rem_cred = 0 AND valor_reservado = 0 THEN v_uid ELSE encerrado_por END
     WHERE id = v_cred.id;
    INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
           id_pendencia, tipo_evento, id_int_origem, id_int_destino, id_movimento_ref, motivo_evento)
    VALUES (v_cred.id_cliente, v_cred.id_int, v_valor, 'DEBITO', 'MANUAL', p_observacao, v_uid,
           v_cred.id, 'DEVOLUCAO', v_cred.id_int, v_p.id_int, v_mc_debito_id, p_motivo);

    PERFORM public.cc__timeline(v_p.id_int, v_p.id_cliente,
      format('🔗 Débito de R$ %s abatido com crédito da proposta #%s.', to_char(v_valor,'FM999999990.00'), v_cred.id_int), v_uid);
    IF v_cred.id_int <> v_p.id_int THEN
      PERFORM public.cc__timeline(v_cred.id_int, v_cred.id_cliente,
        format('🔗 Crédito de R$ %s usado para abater débito da proposta #%s.', to_char(v_valor,'FM999999990.00'), v_p.id_int), v_uid);
    END IF;

  ELSIF p_modo = 'CANCELAMENTO' THEN
    PERFORM public.cc__assert_permissao(v_uid, 'financeiro.resolver_credito');
    SELECT * INTO v_p FROM public.conta_corrente_pendencias WHERE id = p_id_pendencia FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'CC_PENDENCIA: não encontrada'; END IF;
    PERFORM public.cc__assert_escopo_empresa(v_uid, v_p.id_int);
    IF v_p.valor_reservado > 0 THEN RAISE EXCEPTION 'CC_RESERVA_ATIVA: libere a reserva antes de cancelar'; END IF;
    v_free := v_p.valor_saldo;
    IF v_free > 0 THEN
      INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
             id_pendencia, tipo_evento, id_int_origem, motivo_evento)
      VALUES (v_p.id_cliente, v_p.id_int, v_free,
             CASE WHEN v_p.direcao = 'FAVOR_CLIENTE' THEN 'DEBITO' ELSE 'CREDITO' END,
             'MANUAL', p_observacao, v_uid, v_p.id, 'CANCELAMENTO', v_p.id_int, p_motivo);
    END IF;
    UPDATE public.conta_corrente_pendencias
       SET valor_saldo = 0, status = 'CANCELADA', encerrado_em = now(), encerrado_por = v_uid,
           motivo_encerramento = p_motivo, atualizado_em = now()
     WHERE id = p_id_pendencia;
    PERFORM public.cc__timeline(v_p.id_int, v_p.id_cliente,
      format('🚫 Pendência cancelada. Motivo: %s.', COALESCE(p_motivo,'—')), v_uid);

  ELSIF p_modo = 'ESTORNO' THEN
    PERFORM public.cc__assert_permissao(v_uid, '__ADMIN__');   -- v1: somente admin/superadmin
    IF p_id_movimento_ref IS NULL THEN RAISE EXCEPTION 'CC_ESTORNO: id_movimento_ref obrigatório'; END IF;
    SELECT * INTO v_ref FROM public.movimento_credito WHERE id = p_id_movimento_ref AND id_pendencia = p_id_pendencia;
    IF NOT FOUND THEN RAISE EXCEPTION 'CC_ESTORNO: movimento não encontrado na pendência'; END IF;
    IF v_ref.tipo_evento NOT IN ('USO_PEDIDO','DEVOLUCAO','BONIFICACAO','BAIXA') THEN
      RAISE EXCEPTION 'CC_ESTORNO: só é possível estornar eventos de resolução';
    END IF;
    SELECT * INTO v_p FROM public.conta_corrente_pendencias WHERE id = p_id_pendencia FOR UPDATE;
    PERFORM public.cc__assert_escopo_empresa(v_uid, v_p.id_int);
    INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
           id_pendencia, tipo_evento, id_int_origem, id_movimento_ref, motivo_evento)
    VALUES (v_p.id_cliente, v_p.id_int, v_ref.valor,
           CASE WHEN v_ref.tipo = 'CREDITO' THEN 'DEBITO' ELSE 'CREDITO' END,
           'MANUAL', p_observacao, v_uid, v_p.id, 'ESTORNO', v_p.id_int, p_id_movimento_ref, p_motivo);
    UPDATE public.conta_corrente_pendencias
       SET valor_saldo = valor_saldo + v_ref.valor,
           status = public.cc__status(valor_original, valor_saldo + v_ref.valor, valor_reservado),
           atualizado_em = now(), encerrado_em = NULL, encerrado_por = NULL
     WHERE id = p_id_pendencia;
    PERFORM public.cc__timeline(v_p.id_int, v_p.id_cliente,
      format('♻️ Estorno de R$ %s (movimento #%s). Saldo reaberto.', to_char(v_ref.valor,'FM999999990.00'), p_id_movimento_ref), v_uid);
  ELSE
    RAISE EXCEPTION 'CC_MODO: modo inválido %', p_modo;
  END IF;
END; $$;

-- =====================================================================================
-- SEÇÃO D.4 — Execução das RPCs: apenas usuários autenticados (nunca anon).
--   Puramente aditivo/habilitante — não revoga nada de tabela existente.
-- =====================================================================================
REVOKE ALL ON FUNCTION public.cc_abrir_pendencia(bigint,bigint,uuid,text,numeric,text)     FROM public, anon;
REVOKE ALL ON FUNCTION public.cc_usar_pendencia(bigint,numeric,text,bigint,uuid,uuid,text)  FROM public, anon;
REVOKE ALL ON FUNCTION public.cc_encerrar_pendencia(bigint,text,numeric,bigint,uuid,text,text,bigint) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.cc_abrir_pendencia(bigint,bigint,uuid,text,numeric,text)     TO authenticated;
GRANT EXECUTE ON FUNCTION public.cc_usar_pendencia(bigint,numeric,text,bigint,uuid,uuid,text)  TO authenticated;
GRANT EXECUTE ON FUNCTION public.cc_encerrar_pendencia(bigint,text,numeric,bigint,uuid,text,text,bigint) TO authenticated;
REVOKE ALL ON FUNCTION public.cc__assert_permissao(uuid,text) FROM public, anon;
REVOKE ALL ON FUNCTION public.cc__timeline(bigint,bigint,text,uuid) FROM public, anon;
REVOKE ALL ON FUNCTION public.cc__valor_pago(bigint) FROM public, anon;
REVOKE ALL ON FUNCTION public.cc__id_empresa_proposta(bigint) FROM public, anon;
REVOKE ALL ON FUNCTION public.cc__assert_escopo_empresa(uuid,bigint) FROM public, anon;
REVOKE ALL ON FUNCTION public.cc__total_soberano_proposta(bigint) FROM public, anon;

-- =====================================================================================
-- SEÇÃO E — RPCs que gravam em movimento_credito SEM passar por uma linha de
--   conta_corrente_pendencias (crédito/débito avulso — origem=AJUSTE/SISTEMA,
--   id_pendencia NULL). Existem para que o cutover (1b) possa revogar
--   INSERT/UPDATE/DELETE diretos em movimento_credito para `anon` e
--   `authenticated` sem quebrar os fluxos que gravam na razão fora do fluxo
--   de pendências:
--     1) ajuste-credito (avulso, admin/superadmin)      → mc_ajuste_avulso_criar
--     2) estorno-credito (avulso, admin/superadmin)     → mc_ajuste_avulso_estornar
--     3) confirmar (fallback [ABATIMENTO_DEBITO:x] de
--        cobranças anteriores a este refactor)          → mc_confirmar_abatimento_legado
--     4) usar-credito (consumo de crédito avulso como
--        E-Crédito — NÃO é legado, é caminho ativo:      → mc_usar_credito_avulso
--        ver correção da divergência de saldo abaixo)
--   Após o cutover, TODA gravação em movimento_credito ocorre exclusivamente
--   por RPC SECURITY DEFINER — nenhuma mais por INSERT/UPDATE direto do cliente.
-- =====================================================================================

-- E.1 — Ajuste avulso: criação (substitui INSERT direto + dedup por janela de
-- 60s em registrarMovimento/ajuste-credito). Idempotência por chave persistida.
CREATE OR REPLACE FUNCTION public.mc_ajuste_avulso_criar(
  p_id_cliente bigint, p_tipo text, p_valor numeric, p_observacao text, p_chave_idempotencia uuid)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_existente bigint;
  v_new_id bigint;
BEGIN
  PERFORM public.cc__assert_permissao(v_uid, '__ADMIN__');   -- mesma regra da rota atual: admin/superadmin
  IF p_id_cliente IS NULL OR p_tipo IS NULL OR p_valor IS NULL OR p_chave_idempotencia IS NULL THEN
    RAISE EXCEPTION 'MC_PARAMS: id_cliente, tipo, valor e chave_idempotencia são obrigatórios';
  END IF;
  IF p_tipo NOT IN ('CREDITO','DEBITO') THEN RAISE EXCEPTION 'MC_TIPO: tipo inválido % (use CREDITO ou DEBITO)', p_tipo; END IF;
  IF p_valor <= 0 THEN RAISE EXCEPTION 'MC_VALOR: valor deve ser maior que zero'; END IF;
  IF p_observacao IS NULL OR btrim(p_observacao) = '' THEN RAISE EXCEPTION 'MC_OBS: observação é obrigatória para este ajuste'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.clientes WHERE id_cliente = p_id_cliente) THEN
    RAISE EXCEPTION 'MC_CLIENTE: cliente % não encontrado', p_id_cliente;
  END IF;

  SELECT id INTO v_existente FROM public.movimento_credito WHERE chave_idempotencia = p_chave_idempotencia;
  IF FOUND THEN RETURN v_existente; END IF;

  INSERT INTO public.movimento_credito
    (id_cliente, id_int, valor, tipo, origem, observacao, created_by, cancelado, chave_idempotencia)
  VALUES (p_id_cliente, NULL, round(p_valor,2), p_tipo, 'AJUSTE', btrim(p_observacao), v_uid, false, p_chave_idempotencia)
  RETURNING id INTO v_new_id;

  RETURN v_new_id;
END; $$;

-- E.2 — Ajuste avulso: estorno por lançamento compensatório (substitui INSERT
-- direto em estornarMovimentoCredito/estorno-credito). Escopo restrito a
-- movimentos avulsos (origem=AJUSTE, sem proposta) — movimentos vinculados a
-- pendência são estornados por cc_encerrar_pendencia(ESTORNO), não por aqui.
-- Idempotência já garantida por ux_mc_estorno_unico (id_movimento_ref único).
CREATE OR REPLACE FUNCTION public.mc_ajuste_avulso_estornar(p_id_movimento bigint, p_observacao text DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_mov public.movimento_credito%ROWTYPE;
  v_existente bigint;
  v_saldo numeric;
  v_new_id bigint;
BEGIN
  PERFORM public.cc__assert_permissao(v_uid, '__ADMIN__');   -- v1: somente admin/superadmin
  IF p_id_movimento IS NULL THEN RAISE EXCEPTION 'MC_PARAMS: id_movimento é obrigatório'; END IF;

  SELECT * INTO v_mov FROM public.movimento_credito WHERE id = p_id_movimento FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'MC_NAOENCONTRADO: movimento % não encontrado', p_id_movimento; END IF;
  IF v_mov.origem <> 'AJUSTE' OR v_mov.id_int IS NOT NULL THEN
    RAISE EXCEPTION 'MC_ESCOPO: apenas movimentos avulsos (origem=AJUSTE, sem proposta) podem ser estornados por esta função';
  END IF;
  -- Legado: registros cancelados pelo mecanismo antigo (UPDATE cancelado=true,
  -- anterior à correção para lançamento compensatório) não podem ser reestornados.
  IF v_mov.cancelado THEN RAISE EXCEPTION 'MC_CANCELADO: movimento já está cancelado'; END IF;

  SELECT id INTO v_existente FROM public.movimento_credito
   WHERE id_movimento_ref = p_id_movimento AND tipo_evento = 'ESTORNO';
  IF FOUND THEN RETURN v_existente; END IF;

  IF v_mov.tipo = 'CREDITO' THEN
    SELECT COALESCE(SUM(CASE WHEN tipo = 'CREDITO' THEN valor WHEN tipo = 'DEBITO' THEN -valor ELSE 0 END), 0)
      INTO v_saldo
      FROM public.movimento_credito
     WHERE id_cliente = v_mov.id_cliente AND cancelado = false;
    IF GREATEST(v_saldo, 0) - v_mov.valor < 0 THEN
      RAISE EXCEPTION 'MC_SALDO_INSUFICIENTE: saldo atual (R$ %) insuficiente para estornar R$ % — pode já ter sido utilizado', GREATEST(v_saldo,0), v_mov.valor;
    END IF;
  END IF;

  INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
         id_movimento_ref, tipo_evento)
  VALUES (v_mov.id_cliente, v_mov.id_int, v_mov.valor,
         CASE WHEN v_mov.tipo = 'CREDITO' THEN 'DEBITO' ELSE 'CREDITO' END,
         'AJUSTE', COALESCE(p_observacao, format('Estorno do movimento #%s.', p_id_movimento)), v_uid,
         p_id_movimento, 'ESTORNO')
  RETURNING id INTO v_new_id;

  RETURN v_new_id;
END; $$;

-- E.2b — Consumo de crédito AVULSO (origem=AJUSTE/SISTEMA, sem pendência)
-- como pagamento de proposta (E-Crédito). Corrige a divergência entre o
-- saldo total exibido no banner/modal (getSaldoCredito/getSaldoContaCorrente,
-- que somam TODA a razão do cliente) e o saldo que
-- /api/cobrancas/usar-credito conseguia efetivamente consumir (que só
-- enxergava conta_corrente_pendencias: um cliente com crédito 100% avulso
-- (lançado por mc_ajuste_avulso_criar, sem nenhuma pendência aberta) fazia o
-- servidor calcular R$ 0,00 disponível, e a cobrança falhava com "Saldo
-- insuficiente" mesmo o banner mostrando saldo > 0).
--
-- Mesma permissão de cc_usar_pendencia(CREDITO_IMEDIATO): 'credito.usar' —
-- consumir crédito já existente não é operação administrativa como CRIAR ou
-- ESTORNAR um ajuste (mc_ajuste_avulso_criar/estornar exigem __ADMIN__).
--
-- p_id_pagamento é OBRIGATÓRIO (não tem DEFAULT — precisa vir antes dos
-- parâmetros opcionais na assinatura). A linha é travada com FOR UPDATE antes
-- de qualquer decisão: mesma regra "nunca UPDATE/decide às cegas" já usada em
-- cc_usar_pendencia(RESERVA_DEBITO) para pagamentos_v2 — rejeita CANCELADO e
-- valida cliente/proposta/empresa contra a linha travada, nunca só o payload.
--
-- Idempotência por id_pagamento_destino: se este pagamento já tem um
-- USO_PEDIDO avulso (tipo_evento='USO_PEDIDO' AND id_pendencia IS NULL — a
-- marca exclusiva desta função; USO_PEDIDO de cc_usar_pendencia sempre tem
-- id_pendencia preenchido, nunca colide), retorna o movimento existente sem
-- debitar de novo. Checada antes das demais validações de negócio: uma
-- repetição de operação já concluída deve retornar sucesso mesmo que o
-- pagamento tenha mudado de estado depois.
--
-- Não há uma linha de saldo dedicada para crédito avulso (diferente de
-- conta_corrente_pendencias.valor_saldo, mantida por FOR UPDATE na própria
-- linha) — por isso trava também o cliente (public.clientes) para serializar
-- concorrência ENTRE pagamentos diferentes do mesmo cliente (o lock em
-- pagamentos_v2 só serializa chamadas repetidas para o MESMO pagamento).
-- Recalcula o saldo real de TODA a razão sob a trava do cliente (mesma
-- fórmula de getSaldoCredito/getSaldoContaCorrente) e só então grava o
-- DEBITO — impede duplo uso mesmo em requisições concorrentes.
CREATE OR REPLACE FUNCTION public.mc_usar_credito_avulso(
  p_id_cliente bigint, p_valor numeric, p_id_pagamento uuid,
  p_id_int_destino bigint DEFAULT NULL, p_observacao text DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_valor numeric;
  v_saldo numeric;
  v_pag public.pagamentos_v2%ROWTYPE;
  v_existente bigint;
  v_new_id bigint;
BEGIN
  PERFORM public.cc__assert_permissao(v_uid, 'credito.usar');
  IF p_id_cliente IS NULL OR p_valor IS NULL OR p_id_pagamento IS NULL THEN
    RAISE EXCEPTION 'MC_PARAMS: id_cliente, valor e id_pagamento são obrigatórios';
  END IF;
  v_valor := round(p_valor, 2);
  IF v_valor < 0.01 THEN RAISE EXCEPTION 'CC_VALOR_MINIMO: uso mínimo é R$ 0,01'; END IF;

  SELECT * INTO v_pag FROM public.pagamentos_v2 WHERE id = p_id_pagamento FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'CC_COBRANCA: pagamento % não encontrado', p_id_pagamento; END IF;

  SELECT id INTO v_existente FROM public.movimento_credito
   WHERE id_pagamento_destino = p_id_pagamento
     AND tipo_evento = 'USO_PEDIDO'
     AND id_pendencia IS NULL;
  IF FOUND THEN RETURN v_existente; END IF;

  IF v_pag.status = 'CANCELADO' THEN
    RAISE EXCEPTION 'CC_COBRANCA_CANCELADA: pagamento % está cancelado', p_id_pagamento;
  END IF;
  IF v_pag.id_cliente IS DISTINCT FROM p_id_cliente THEN
    RAISE EXCEPTION 'CC_CLIENTE_DIVERGENTE: pagamento % pertence a outro cliente', p_id_pagamento;
  END IF;
  IF p_id_int_destino IS NOT NULL AND v_pag.id_int IS DISTINCT FROM p_id_int_destino THEN
    RAISE EXCEPTION 'CC_PROPOSTA_DIVERGENTE: pagamento % não pertence à proposta de destino informada', p_id_pagamento;
  END IF;
  IF v_pag.id_empresa IS NOT NULL AND v_pag.id_empresa <> public.cc__id_empresa_proposta(v_pag.id_int) THEN
    RAISE EXCEPTION 'CC_EMPRESA_DIVERGENTE: pagamento % pertence a outra empresa', p_id_pagamento;
  END IF;

  PERFORM 1 FROM public.clientes WHERE id_cliente = p_id_cliente FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'MC_CLIENTE: cliente % não encontrado', p_id_cliente; END IF;

  SELECT COALESCE(SUM(CASE WHEN tipo = 'CREDITO' THEN valor WHEN tipo = 'DEBITO' THEN -valor ELSE 0 END), 0)
    INTO v_saldo
    FROM public.movimento_credito
   WHERE id_cliente = p_id_cliente AND cancelado = false;

  IF v_saldo < v_valor THEN
    RAISE EXCEPTION 'CC_SALDO_INSUFICIENTE: saldo R$ % < solicitado R$ %', GREATEST(v_saldo,0), v_valor;
  END IF;

  INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
         tipo_evento, id_int_destino, id_pagamento_destino, motivo_evento)
  VALUES (p_id_cliente, v_pag.id_int, v_valor, 'DEBITO', 'SISTEMA',
         COALESCE(p_observacao, 'Crédito avulso aplicado como pagamento.'), v_uid,
         'USO_PEDIDO', v_pag.id_int, p_id_pagamento, 'USO_CREDITO_AVULSO')
  RETURNING id INTO v_new_id;

  PERFORM public.cc__timeline(v_pag.id_int, p_id_cliente,
    format('💰 Crédito avulso de R$ %s aplicado como pagamento.', to_char(v_valor,'FM999999990.00')), v_uid);

  RETURN v_new_id;
END; $$;

-- E.3 — Fallback legado de abatimento de débito em /api/cobrancas/confirmar
-- (cobranças criadas com o marcador [ABATIMENTO_DEBITO:x] antes deste
-- refactor, sem reserva formal via cc_usar_pendencia). Substitui o INSERT
-- direto + verificação por `ilike observacao` por uma chave determinística
-- persistida (o próprio id do pagamento, já único) via ux_mc_abatimento_legado_unico.
CREATE OR REPLACE FUNCTION public.mc_confirmar_abatimento_legado(
  p_id_cliente bigint, p_id_int bigint, p_id_pagamento uuid, p_valor numeric, p_observacao text)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_existente bigint;
  v_new_id bigint;
BEGIN
  PERFORM public.cc__assert_permissao(v_uid, 'conferencia.confirm');
  IF p_id_cliente IS NULL OR p_id_pagamento IS NULL OR p_valor IS NULL THEN
    RAISE EXCEPTION 'MC_PARAMS: id_cliente, id_pagamento e valor são obrigatórios';
  END IF;
  IF p_valor <= 0 THEN RAISE EXCEPTION 'MC_VALOR: valor deve ser maior que zero'; END IF;

  SELECT id INTO v_existente FROM public.movimento_credito
   WHERE id_pagamento_destino = p_id_pagamento AND tipo_evento = 'ABATIMENTO_LEGADO';
  IF FOUND THEN RETURN v_existente; END IF;

  INSERT INTO public.movimento_credito (id_cliente, id_int, valor, tipo, origem, observacao, created_by,
         tipo_evento, id_pagamento_destino)
  VALUES (p_id_cliente, p_id_int, round(p_valor,2), 'CREDITO', 'SISTEMA', p_observacao, v_uid,
         'ABATIMENTO_LEGADO', p_id_pagamento)
  RETURNING id INTO v_new_id;

  IF p_id_int IS NOT NULL THEN
    PERFORM public.cc__timeline(p_id_int, p_id_cliente,
      format('💳 Débito de R$ %s abatido na conta corrente após confirmação do pagamento.', to_char(round(p_valor,2),'FM999999990.00')), v_uid);
  END IF;

  RETURN v_new_id;
END; $$;

REVOKE ALL ON FUNCTION public.mc_ajuste_avulso_criar(bigint,text,numeric,text,uuid) FROM public, anon;
REVOKE ALL ON FUNCTION public.mc_ajuste_avulso_estornar(bigint,text) FROM public, anon;
REVOKE ALL ON FUNCTION public.mc_usar_credito_avulso(bigint,numeric,uuid,bigint,text) FROM public, anon;
REVOKE ALL ON FUNCTION public.mc_confirmar_abatimento_legado(bigint,bigint,uuid,numeric,text) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.mc_ajuste_avulso_criar(bigint,text,numeric,text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mc_ajuste_avulso_estornar(bigint,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mc_usar_credito_avulso(bigint,numeric,uuid,bigint,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mc_confirmar_abatimento_legado(bigint,bigint,uuid,numeric,text) TO authenticated;

COMMIT;
