-- Migration: Criar infraestrutura para Preço Fixo por Cliente e Produto
-- Data: 2026-07-13

-- 1. Adicionar flag usa_preco_fixo na tabela de clientes
ALTER TABLE public.clientes 
ADD COLUMN IF NOT EXISTS usa_preco_fixo BOOLEAN DEFAULT false;

-- 2. Criar tabela clientes_precos_fixos
-- NOTA: Verifique se os tipos de id_cliente e id_produto coincidem com as PKs reais!
CREATE TABLE IF NOT EXISTS public.clientes_precos_fixos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL, -- VERIFICAR SE A PK DE clientes É BIGINT
    id_produto BIGINT NOT NULL, -- VERIFICAR SE A PK DE produtos É BIGINT
    preco_fixo NUMERIC(10,2) NOT NULL, -- Ajustar precisão se produtos.valorUnt for diferente
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT fk_cliente_preco_fixo FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente) ON DELETE CASCADE,
    CONSTRAINT fk_produto_preco_fixo FOREIGN KEY (id_produto) REFERENCES public.produtos(id_produto) ON DELETE CASCADE,
    CONSTRAINT uk_cliente_produto_preco UNIQUE (id_cliente, id_produto)
);

-- 3. Habilitar RLS (Row Level Security) - Ajuste conforme as policies do projeto
ALTER TABLE public.clientes_precos_fixos ENABLE ROW LEVEL SECURITY;

-- Policy basica para leitura e escrita autenticada (ajuste se necessario)
CREATE POLICY "Enable read/write for authenticated users only" ON public.clientes_precos_fixos
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
